### ISSUE TITLE
.NetCore Sample运行有bug

### ISSUE THREAD

**Issue by QQ897878763** [WeihanLi/WeihanLi.Npoi#13]
Index was outside the bounds of the array.   
at WeihanLi.Npoi.CsvHelper.ToEntityList[TEntity](String filePath) in D:\Code\Study\NPOI\WeihanLi.Npoi-dev\src\WeihanLi.Npoi\CsvHelper.cs:line 175
   at DotNetCoreSample.Program.Main(String[] args) in D:\Code\Study\NPOI\WeihanLi.Npoi-dev\samples\DotNetCoreSample\Program.cs:line 60

**Comment by WeihanLi** [comment]
感谢反馈

**Comment by WeihanLi** [comment]
已经修复，感谢反馈
